### ISSUE TITLE
Checklist de cosas que hay que hacer

### ISSUE THREAD

**Issue by davidglezz** [Arquisoft/VotingSystem_3a#13]
Para que nadie se escaquee y diga que no sabia que hacer. Cada cual es libre para añadir nuevas tareas.
- Codigo
  - [ ] Integrar esa parte nueva que me comentábais
  - [ ] Arreglar Test
  - [ ] Comprobar que cada subsistema funciona correctamente.
    - [ ] Censuses
    - [ ] Voters
    - [ ] VoteCounting
    - [ ] VotingSystem
  - [ ] Terminar de implementar unas cosas de VoteCounting.
  - [ ] Probar que ya se puede hacer la historia de usuario básica para un video demostrativo.
- Documentación
  - [ ] Comprobar nombres de paquetes, ...
- Otros
  - [ ] Video

**Comment by davidglezz** [comment]
Me confundi de repositorio
